media_folder: public/images
public_folder: /images
backend:
  name: git-gateway
  branch: development
collections:
  - name: translations
    label: Translations
    label_singular: Translation
    folder: source/i18n/locales
    create: false
    delete: false
    extension: json
    fields:
      - label: answers.features.answer.description
        name: answers.features.answer.description
        widget: text
      - label: answers.features.answer.title
        name: answers.features.answer.title
        widget: text
      - label: answers.features.ask.description
        name: answers.features.ask.description
        widget: text
      - label: answers.features.ask.title
        name: answers.features.ask.title
        widget: text
      - label: answers.features.headline
        name: answers.features.headline
        widget: text
      - label: answers.features.review.description
        name: answers.features.review.description
        widget: text
      - label: answers.features.review.title
        name: answers.features.review.title
        widget: text
      - label: answers.features.search.description
        name: answers.features.search.description
        widget: text
      - label: answers.features.search.title
        name: answers.features.search.title
        widget: text
      - label: answers.features.title
        name: answers.features.title
        widget: text
      - label: answers.features.translate.description
        name: answers.features.translate.description
        widget: text
      - label: answers.features.translate.title
        name: answers.features.translate.title
        widget: text
      - label: answers.headline
        name: answers.headline
        widget: text
      - label: answers.pitch
        name: answers.pitch
        widget: text
      - label: answers.stripe.accessToInformation
        name: answers.stripe.accessToInformation
        widget: text
      - label: answers.title
        name: answers.title
        widget: text
      - label: answers.whatwedo.description
        name: answers.whatwedo.description
        widget: text
      - label: answers.whatwedo.title
        name: answers.whatwedo.title
        widget: text
      - label: blog.backHomeLink
        name: blog.backHomeLink
        widget: text
      - label: blog.headline
        name: blog.headline
        widget: text
      - label: blog.readMore
        name: blog.readMore
        widget: text
      - label: blog.subline
        name: blog.subline
        widget: text
      - label: blog.title
        name: blog.title
        widget: text
      - label: buttons.joinUs
        name: buttons.joinUs
        widget: text
      - label: home.challenges.refugees.headline
        name: home.challenges.refugees.headline
        widget: text
      - label: home.challenges.refugees.inclusion.description
        name: home.challenges.refugees.inclusion.description
        widget: text
      - label: home.challenges.refugees.inclusion.title
        name: home.challenges.refugees.inclusion.title
        widget: text
      - label: home.challenges.refugees.information.description
        name: home.challenges.refugees.information.description
        widget: text
      - label: home.challenges.refugees.information.title
        name: home.challenges.refugees.information.title
        widget: text
      - label: home.challenges.refugees.language.description
        name: home.challenges.refugees.language.description
        widget: text
      - label: home.challenges.refugees.language.title
        name: home.challenges.refugees.language.title
        widget: text
      - label: home.challenges.refugees.social.description
        name: home.challenges.refugees.social.description
        widget: text
      - label: home.challenges.refugees.social.title
        name: home.challenges.refugees.social.title
        widget: text
      - label: home.challenges.society.fear.description
        name: home.challenges.society.fear.description
        widget: text
      - label: home.challenges.society.fear.title
        name: home.challenges.society.fear.title
        widget: text
      - label: home.challenges.society.headline
        name: home.challenges.society.headline
        widget: text
      - label: home.challenges.society.polarization.description
        name: home.challenges.society.polarization.description
        widget: text
      - label: home.challenges.society.polarization.title
        name: home.challenges.society.polarization.title
        widget: text
      - label: home.challenges.society.prejudice.description
        name: home.challenges.society.prejudice.description
        widget: text
      - label: home.challenges.society.prejudice.title
        name: home.challenges.society.prejudice.title
        widget: text
      - label: home.challenges.society.racism.description
        name: home.challenges.society.racism.description
        widget: text
      - label: home.challenges.society.racism.title
        name: home.challenges.society.racism.title
        widget: text
      - label: home.challenges.supporters.confusion.description
        name: home.challenges.supporters.confusion.description
        widget: text
      - label: home.challenges.supporters.confusion.title
        name: home.challenges.supporters.confusion.title
        widget: text
      - label: home.challenges.supporters.frustration.description
        name: home.challenges.supporters.frustration.description
        widget: text
      - label: home.challenges.supporters.frustration.title
        name: home.challenges.supporters.frustration.title
        widget: text
      - label: home.challenges.supporters.headline
        name: home.challenges.supporters.headline
        widget: text
      - label: home.challenges.supporters.information.description
        name: home.challenges.supporters.information.description
        widget: text
      - label: home.challenges.supporters.information.title
        name: home.challenges.supporters.information.title
        widget: text
      - label: home.challenges.supporters.isolation.description
        name: home.challenges.supporters.isolation.description
        widget: text
      - label: home.challenges.supporters.isolation.title
        name: home.challenges.supporters.isolation.title
        widget: text
      - label: home.challenges.title
        name: home.challenges.title
        widget: text
      - label: home.factDisplaced
        name: home.factDisplaced
        widget: text
      - label: home.factIncreaseOfHate
        name: home.factIncreaseOfHate
        widget: text
      - label: home.factSupportersTranslation
        name: home.factSupportersTranslation
        widget: text
      - label: home.headline
        name: home.headline
        widget: text
      - label: home.join.newsletter.email
        name: home.join.newsletter.email
        widget: text
      - label: home.join.newsletter.ht
        name: home.join.newsletter.ht
        widget: text
      - label: home.join.newsletter.id
        name: home.join.newsletter.id
        widget: text
      - label: home.join.newsletter.submitLabel
        name: home.join.newsletter.submitLabel
        widget: text
      - label: home.join.title
        name: home.join.title
        widget: text
      - label: home.pitch
        name: home.pitch
        widget: text
      - label: home.projects.answers.intro
        name: home.projects.answers.intro
        widget: text
      - label: home.projects.answers.title
        name: home.projects.answers.title
        widget: text
      - label: home.projects.comingSoon
        name: home.projects.comingSoon
        widget: text
      - label: home.projects.connect.intro
        name: home.projects.connect.intro
        widget: text
      - label: home.projects.connect.title
        name: home.projects.connect.title
        widget: text
      - label: home.projects.title
        name: home.projects.title
        widget: text
      - label: home.title
        name: home.title
        widget: text
      - label: home.what_you_can_do.description
        name: home.what_you_can_do.description
        widget: text
      - label: home.what_you_can_do.title
        name: home.what_you_can_do.title
        widget: text
      - label: home.whatwedo.description1
        name: home.whatwedo.description1
        widget: text
      - label: home.whatwedo.description2
        name: home.whatwedo.description2
        widget: text
      - label: home.whatwedo.title
        name: home.whatwedo.title
        widget: text
      - label: impress.address
        name: impress.address
        widget: text
      - label: impress.contact
        name: impress.contact
        widget: text
      - label: impress.copyright
        name: impress.copyright
        widget: text
      - label: impress.headline
        name: impress.headline
        widget: text
      - label: impress.intro
        name: impress.intro
        widget: text
      - label: impress.title
        name: impress.title
        widget: text
      - label: layout.footer.impressLink
        name: layout.footer.impressLink
        widget: text
      - label: layout.topMenu.blogLink
        name: layout.topMenu.blogLink
        widget: text
      - label: layout.topMenu.homeLink
        name: layout.topMenu.homeLink
        widget: text
      - label: title
        name: title
        widget: string
    editor:
      preview: false
  - name: blog-de
    label: Blog DE
    folder: content/blog/de
    extension: md
    create: true
    slug: '{{slug}}'
    fields:
      - label: Language
        name: language
        widget: select
        options:
          - en
          - de
          - ar
      - label: URL Slug
        name: title
        widget: string
      - label: Title
        name: headline
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Readable Date
        name: readable_date
        widget: string
      - label: Published
        name: published
        widget: boolean
      - label: Feature Image
        name: image
        widget: image
      - label: Teaser
        name: teaser
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: blog-en
    label: Blog EN
    folder: content/blog/en
    extension: md
    create: true
    slug: '{{slug}}'
    fields:
      - label: Language
        name: language
        widget: select
        options:
          - en
          - de
          - ar
      - label: URL Slug
        name: title
        widget: string
      - label: Title
        name: headline
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Readable Date
        name: readable_date
        widget: string
      - label: Published
        name: published
        widget: boolean
      - label: Feature Image
        name: image
        widget: image
      - label: teaser
        name: teaser
        widget: string
      - label: Body
        name: body
        widget: markdown
  - name: blog-ar
    label: Blog AR
    folder: content/blog/ar
    extension: md
    create: true
    slug: '{{slug}}'
    fields:
      - label: Language
        name: language
        widget: select
        options:
          - en
          - de
          - ar
      - label: URL Slug
        name: title
        widget: string
      - label: Title
        name: headline
        widget: string
      - label: Subtitle
        name: subtitle
        widget: string
      - label: Author
        name: author
        widget: string
      - label: Date
        name: date
        widget: date
      - label: Readable Date
        name: readable_date
        widget: string
      - label: Published
        name: published
        widget: boolean
      - label: Feature Image
        name: image
        widget: image
      - label: Teaser
        name: teaser
        widget: string
      - label: Body
        name: body
        widget: markdown
