publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"
backend:
  name: git-gateway
  branch: development
collections:
  - name: "translations"
    label: "Translations"
    label_singular: "Translation"
    folder: "source/i18n/locales"
    create: false
    delete: false
    extension: json
    fields:
      - { label: "Contents", name: "body", widget: "text" }
    editor:
      preview: false
