backend:
  name: git-gateway
  branch: development
  publish_mode: editorial_workflow
  media_folder: "public/images"
  public_folder: "/images"
collections:
  - name: "translations"
    label: "Translations"
    folder: "source/i18n/locales"
    create: false
    fields:
      - { label: "Contents", name: "contents", widget: "text" }
